-- 코드를 입력하세요
# select 
# # (case when USER_ID = NULL then NULL END) as USER_ID,
# IFNULL(USER_ID,null) As USER_ID,
# # USER_ID,
# PRODUCT_ID,
# DATE_FORMAT(SALES_DATE,"%Y-%m-%d") AS SALES_DATE,
# SALES_AMOUNT
# from ((SELECT USER_ID, PRODUCT_ID , SALES_DATE,SALES_AMOUNT FROM ONLINE_SALE) 
# UNION ALL 
# (SELECT NULL, PRODUCT_ID, SALES_DATE ,SALES_AMOUNT FROM OFFLINE_SALE)) as A
# where DATE_FORMAT(SALES_DATE,"%Y-%m") = "2022-03"
# order by SALES_DATE , PRODUCT_ID , USER_ID
# ;
-- 코드를 입력하세요
SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALES_DATE, PRODUCT_ID, IFNULL(USER_ID, NULL) AS USER_ID, SALES_AMOUNT
FROM ONLINE_SALE
WHERE YEAR(SALES_DATE) = 2022 AND MONTH(SALES_DATE) = 3
UNION ALL
SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALES_DATE, PRODUCT_ID, NULL, SALES_AMOUNT 
FROM OFFLINE_SALE
WHERE YEAR(SALES_DATE) = 2022 AND MONTH(SALES_DATE) = 3
ORDER BY SALES_DATE ASC, PRODUCT_ID ASC, USER_ID ASC;