-- 코드를 작성해주세요
# (SELECT ID,FISH_TYPE , IFNULL(LENGTH,10) as LENGTH FROM FISH_INFO);
select round(AVG(A.LENGTH),2) as AVERAGE_LENGTH from (SELECT ID,FISH_TYPE , IFNULL(LENGTH,10) as LENGTH FROM FISH_INFO) as A
