-- 코드를 작성해주세요
# 추측해본 결과 아마도 FISH_NAME_INFO에 같은 FISH_NAME이지만 다른 FISH_TYPE인 row가 있는 것 같습니다.
# SELECT FISH_TYPE,COUNT(FISH_TYPE) count FROM FISH_INFO GROUP BY FISH_TYPE
# SELECT A.count FISH_COUNT , B.FISH_NAME FROM 
# SELECT * FROM
# (SELECT FISH_TYPE,COUNT(FISH_TYPE) count FROM FISH_INFO GROUP BY FISH_TYPE) A
# join FISH_NAME_INFO B
# on A.FISH_TYPE = B.FISH_TYPE
# order by FISH_COUNT DESC
# ;
SELECT 
    count(FISH_TYPE) FISH_COUNT,
    A.FISH_NAME
FROM
    (SELECT FISH_INFO.FISH_TYPE,FISH_NAME
    FROM 
        FISH_INFO 
        join 
        FISH_NAME_INFO 
        on 
        FISH_INFO.FISH_TYPE = FISH_NAME_INFO.FISH_TYPE) as A
GROUP BY 
    A.FISH_TYPE, A.FISH_NAME
ORDER BY 
    FISH_COUNT DESC
    
