-- 코드를 입력하세요
# SELECT * FROM FOOD_FACTORY 
#     WHERE SUBSTRING_INDEX(ADDRESS,'" "',-1) = '강원도';
# SELECT SUBSTRING_INDEX(ADDRESS,'" "',-1) FROM FOOD_FACTORY
select FACTORY_ID , FACTORY_NAME ,ADDRESS 
from FOOD_FACTORY
where subString(ADDRESS, 1,3) = '강원도'
order by FACTORY_ID ASC
;