select B.ID , FISH_NAME_INFO.FISH_NAME , B.LENGTH from FISH_NAME_INFO join 
(select FISH_INFO.ID , FISH_INFO.FISH_TYPE ,A.LENGTH from FISH_INFO 
join (select FISH_TYPE, MAX(LENGTH) as LENGTH from FISH_INFO group by FISH_TYPE) as A 
on FISH_INFO.FISH_TYPE = A.FISH_TYPE
where FISH_INFO.LENGTH = A.LENGTH) as B 
on FISH_NAME_INFO.FISH_TYPE = B.FISH_TYPE 
order by B.ID ASC