-- 코드를 작성해주세요
# (SELECT EMP_NO, SUM(SCORE) as SCORE FROM HR_GRADE GROUP BY EMP_NO order by SCORE DESC limit 1)

select B.SCORE, E.EMP_NO,E.EMP_NAME, E.POSITION, E.EMAIL FROM HR_EMPLOYEES as E join (SELECT EMP_NO, SUM(SCORE) as SCORE FROM HR_GRADE GROUP BY EMP_NO order by SCORE DESC limit 1) as B
on E.EMP_NO = B.EMP_NO;